/* report_js.h — client-side filter/sort behaviour, extracted from the Python
 * generator so both renderers behave identically. */
#ifndef SENTINEL_REPORT_JS_H
#define SENTINEL_REPORT_JS_H

static const char REPORT_JS[] =
    "\n"
    "    let activeFilter = 'all';\n"
    "\n"
    "    document.querySelectorAll('.filter-btn').forEach(btn => {{\n"
    "      btn.addEventListener('click', (e) => {{\n"
    "        document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));\n"
    "        btn.classList.add('active');\n"
    "        activeFilter = btn.getAttribute('data-filter');\n"
    "        applyFilters();\n"
    "      }});\n"
    "    }});\n"
    "\n"
    "    function filterPorts(category, btn) {{\n"
    "      document.querySelectorAll('.port-btn').forEach(b => b.classList.remove('active'));\n"
    "      btn.classList.add('active');\n"
    "      const rows = document.querySelectorAll('.port-row');\n"
    "\n"
    "      rows.forEach(r => {{\n"
    "        const sev = r.getAttribute('data-sev') || '';\n"
    "        const cat = r.getAttribute('data-cat') || '';\n"
    "\n"
    "        if (category === 'all') {{\n"
    "          r.style.display = '';\n"
    "        }} else if (category === 'high-crit') {{\n"
    "          r.style.display = (sev === 'critical' || sev === 'high') ? '' : 'none';\n"
    "        }} else if (category === 'containers') {{\n"
    "          r.style.display = (cat.includes('container') || cat.includes('docker')) ? '' : 'none';\n"
    "        }} else if (category === 'database') {{\n"
    "          r.style.display = (cat.includes('database') || cat.includes('storage')) ? '' : 'none';\n"
    "        }}\n"
    "      }});\n"
    "    }}\n"
    "\n"
    "    function handleSearch() {{\n"
    "      applyFilters();\n"
    "    }}\n"
    "\n"
    "    function applyFilters() {{\n"
    "      const query = (document.getElementById('searchInput').value || '').toLowerCase().trim();\n"
    "      const cards = document.querySelectorAll('.card:not(.ports-card)');\n"
    "\n"
    "      cards.forEach(card => {{\n"
    "        const rows = card.querySelectorAll('tbody tr');\n"
    "        let visibleCount = 0;\n"
    "\n"
    "        rows.forEach(row => {{\n"
    "          const sev = (row.getAttribute('data-sev') || '').toLowerCase();\n"
    "          const text = row.innerText.toLowerCase();\n"
    "\n"
    "          const matchesFilter = (activeFilter === 'all' || sev === activeFilter);\n"
    "          const matchesQuery = (!query || text.includes(query));\n"
    "\n"
    "          if (matchesFilter && matchesQuery) {{\n"
    "            row.style.display = '';\n"
    "            visibleCount++;\n"
    "          }} else {{\n"
    "            row.style.display = 'none';\n"
    "          }}\n"
    "        }});\n"
    "\n"
    "        card.style.display = (visibleCount > 0) ? '' : 'none';\n"
    "      }});\n"
    "    }}\n"
    "  \n";

#endif
