/* report_css.h — extracted verbatim from the Python report generator so the
 * C and Python renderers stay visually identical. Generated once; edit
 * sentinel/core/report.py first, then regenerate. */
#ifndef SENTINEL_REPORT_CSS_H
#define SENTINEL_REPORT_CSS_H

static const char REPORT_CSS[] =
    "\n"
    "  :root {\n"
    "    --bg: #0e0e0e;\n"
    "    --surface: #161616;\n"
    "    --surface-raised: #1c1c1c;\n"
    "    --surface-hover: #222222;\n"
    "    --border: #2a2a2a;\n"
    "    --border-strong: #3d3d3d;\n"
    "    --border-silver: #4a4a4a;\n"
    "    --border-focus: #666666;\n"
    "    --text-primary: #e8e4dc;\n"
    "    --text-secondary: #9a948c;\n"
    "    --text-muted: #5e5a54;\n"
    "    --silver: #c5cbd3;\n"
    "    --silver-glow: rgba(197, 203, 211, 0.12);\n"
    "    --accent: #8b3a3a;\n"
    "    --accent-hover: #a14444;\n"
    "    --accent-subtle: rgba(139, 58, 58, 0.18);\n"
    "    --accent-glow: rgba(139, 58, 58, 0.28);\n"
    "    --card-radius: 14px;\n"
    "    --pill-radius: 999px;\n"
    "    --font-serif: \"Newsreader\", Georgia, \"Times New Roman\", serif;\n"
    "    --font-sans: \"IBM Plex Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;\n"
    "    --font-mono: \"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;\n"
    "    --space-xs: 4px;\n"
    "    --space-sm: 8px;\n"
    "    --space-md: 16px;\n"
    "    --space-lg: 24px;\n"
    "    --space-xl: 32px;\n"
    "    --space-xxl: 48px;\n"
    "  }\n"
    "\n"
    "  * { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "\n"
    "  body {\n"
    "    background-color: var(--bg);\n"
    "    color: var(--text-primary);\n"
    "    font-family: var(--font-sans);\n"
    "    font-size: 14px;\n"
    "    line-height: 1.5;\n"
    "    -webkit-font-smoothing: antialiased;\n"
    "    min-height: 100vh;\n"
    "  }\n"
    "\n"
    "  @media (prefers-reduced-motion: reduce) {\n"
    "    * { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; }\n"
    "  }\n"
    "\n"
    "  /* Header */\n"
    "  header {\n"
    "    background: linear-gradient(180deg, #141414 0%, var(--bg) 100%);\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    padding: var(--space-xl) var(--space-lg) var(--space-lg);\n"
    "  }\n"
    "\n"
    "  .header-container {\n"
    "    max-width: 1440px;\n"
    "    margin: 0 auto;\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    gap: var(--space-sm);\n"
    "  }\n"
    "\n"
    "  .brand-row {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    flex-wrap: wrap;\n"
    "    gap: var(--space-md);\n"
    "  }\n"
    "\n"
    "  .brand-group { display: flex; align-items: center; gap: var(--space-md); }\n"
    "\n"
    "  .brand-badge {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 11px;\n"
    "    letter-spacing: 0.08em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--silver);\n"
    "    background: var(--surface-raised);\n"
    "    border: 1px solid var(--border-strong);\n"
    "    padding: 4px 10px;\n"
    "    border-radius: var(--pill-radius);\n"
    "  }\n"
    "\n"
    "  h1 {\n"
    "    font-family: var(--font-serif);\n"
    "    font-size: 28px;\n"
    "    font-weight: 500;\n"
    "    letter-spacing: -0.01em;\n"
    "    color: var(--text-primary);\n"
    "  }\n"
    "\n"
    "  .header-subtitle {\n"
    "    color: var(--text-secondary);\n"
    "    font-size: 13px;\n"
    "    display: flex;\n"
    "    gap: var(--space-sm);\n"
    "    flex-wrap: wrap;\n"
    "    align-items: center;\n"
    "  }\n"
    "\n"
    "  .header-subtitle strong { color: var(--text-primary); }\n"
    "\n"
    "  /* Main Container */\n"
    "  main.wrap {\n"
    "    max-width: 1440px;\n"
    "    margin: 0 auto;\n"
    "    padding: var(--space-xl) var(--space-lg) var(--space-xxl);\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    gap: var(--space-lg);\n"
    "  }\n"
    "\n"
    "  /* Progress & Severity Distribution */\n"
    "  .progress-card {\n"
    "    background: var(--surface);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: var(--card-radius);\n"
    "    padding: var(--space-md) var(--space-lg);\n"
    "    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.35), inset 0 1px 0 rgba(255, 255, 255, 0.03);\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    gap: var(--space-sm);\n"
    "  }\n"
    "\n"
    "  .progress-card-top {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    flex-wrap: wrap;\n"
    "    gap: var(--space-sm);\n"
    "  }\n"
    "\n"
    "  .progress-title {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 12px;\n"
    "    text-transform: uppercase;\n"
    "    letter-spacing: 0.06em;\n"
    "    color: var(--text-secondary);\n"
    "  }\n"
    "\n"
    "  .progress-stats {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 13px;\n"
    "    color: var(--text-primary);\n"
    "  }\n"
    "\n"
    "  .progress-stats span { color: var(--silver); font-weight: 700; }\n"
    "\n"
    "  .progress-bar-bg {\n"
    "    width: 100%;\n"
    "    height: 8px;\n"
    "    background: var(--surface-raised);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 4px;\n"
    "    overflow: hidden;\n"
    "    display: flex;\n"
    "  }\n"
    "\n"
    "  .dist-seg { height: 100%; transition: width 0.3s ease; }\n"
    "\n"
    "  /* Controls Bar */\n"
    "  .controls-bar {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    gap: var(--space-md);\n"
    "    flex-wrap: wrap;\n"
    "    background: var(--surface);\n"
    "    border: 1px solid var(--border);\n"
    "    padding: var(--space-sm) var(--space-md);\n"
    "    border-radius: var(--card-radius);\n"
    "  }\n"
    "\n"
    "  .filter-group { display: flex; gap: var(--space-sm); align-items: center; flex-wrap: wrap; }\n"
    "\n"
    "  .filter-label {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 12px;\n"
    "    color: var(--text-secondary);\n"
    "    margin-right: 4px;\n"
    "    text-transform: uppercase;\n"
    "  }\n"
    "\n"
    "  .pill {\n"
    "    font-family: var(--font-mono);\n"
    "    color: #0e0e0e;\n"
    "    font-weight: 700;\n"
    "    padding: 3px 10px;\n"
    "    border-radius: var(--pill-radius);\n"
    "    font-size: 11px;\n"
    "    border: 1px solid transparent;\n"
    "    cursor: pointer;\n"
    "    transition: all 0.15s ease;\n"
    "  }\n"
    "\n"
    "  .pill:hover { opacity: 0.9; transform: translateY(-1px); }\n"
    "  .pill.active { outline: 2px solid var(--silver); box-shadow: 0 0 8px var(--silver-glow); }\n"
    "  .pill-all { background: var(--silver); color: #0e0e0e; }\n"
    "\n"
    "  .search-input {\n"
    "    background: var(--surface-raised);\n"
    "    border: 1px solid var(--border);\n"
    "    color: var(--text-primary);\n"
    "    padding: 6px 14px;\n"
    "    border-radius: var(--pill-radius);\n"
    "    font-family: var(--font-sans);\n"
    "    font-size: 13px;\n"
    "    outline: none;\n"
    "    width: 260px;\n"
    "    transition: border-color 0.15s ease, box-shadow 0.15s ease;\n"
    "  }\n"
    "\n"
    "  .search-input:focus {\n"
    "    border-color: var(--border-silver);\n"
    "    box-shadow: 0 0 0 2px var(--silver-glow);\n"
    "  }\n"
    "\n"
    "  /* Cards & Ports Panel */\n"
    "  .card {\n"
    "    background: var(--surface);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: var(--card-radius);\n"
    "    overflow: hidden;\n"
    "    box-shadow: 0 4px 24px rgba(0, 0, 0, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.04);\n"
    "    transition: border-color 0.2s ease;\n"
    "  }\n"
    "\n"
    "  .card:hover { border-color: var(--border-strong); }\n"
    "\n"
    "  .card-h {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    padding: var(--space-md) var(--space-lg);\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    background: linear-gradient(90deg, var(--surface) 0%, var(--surface-raised) 100%);\n"
    "    flex-wrap: wrap;\n"
    "    gap: var(--space-sm);\n"
    "  }\n"
    "\n"
    "  .card-h-title { display: flex; align-items: baseline; gap: var(--space-sm); }\n"
    "\n"
    "  .card-h h2 {\n"
    "    font-family: var(--font-serif);\n"
    "    font-size: 18px;\n"
    "    font-weight: 500;\n"
    "    color: var(--text-primary);\n"
    "  }\n"
    "\n"
    "  .badge-subtle {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 11px;\n"
    "    color: var(--text-muted);\n"
    "    background: var(--surface);\n"
    "    border: 1px solid var(--border);\n"
    "    padding: 1px 6px;\n"
    "    border-radius: 4px;\n"
    "  }\n"
    "\n"
    "  .pills { display: flex; gap: var(--space-xs); flex-wrap: wrap; }\n"
    "\n"
    "  /* Ports Specific */\n"
    "  .port-filters { display: flex; gap: 6px; flex-wrap: wrap; }\n"
    "  .port-btn {\n"
    "    background: var(--surface);\n"
    "    border: 1px solid var(--border);\n"
    "    color: var(--text-secondary);\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 11px;\n"
    "    padding: 3px 9px;\n"
    "    border-radius: var(--pill-radius);\n"
    "    cursor: pointer;\n"
    "    transition: all 0.15s ease;\n"
    "  }\n"
    "  .port-btn:hover { background: var(--surface-hover); color: var(--text-primary); }\n"
    "  .port-btn.active {\n"
    "    background: var(--accent-subtle);\n"
    "    border-color: var(--accent);\n"
    "    color: var(--text-primary);\n"
    "    font-weight: 600;\n"
    "  }\n"
    "\n"
    "  .port-badge {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 12px;\n"
    "    font-weight: 600;\n"
    "    color: var(--silver);\n"
    "    background: var(--surface-raised);\n"
    "    border: 1px solid var(--border-strong);\n"
    "    padding: 2px 7px;\n"
    "    border-radius: 4px;\n"
    "    display: inline-block;\n"
    "  }\n"
    "\n"
    "  .service-name { font-weight: 500; color: var(--text-primary); }\n"
    "\n"
    "  .cat-pill {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 10px;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "    background: var(--surface-raised);\n"
    "    padding: 2px 6px;\n"
    "    border-radius: 3px;\n"
    "    border: 1px solid var(--border);\n"
    "  }\n"
    "\n"
    "  /* Table */\n"
    "  .table-wrap { overflow-x: auto; }\n"
    "\n"
    "  table { width: 100%; border-collapse: collapse; font-size: 13px; }\n"
    "\n"
    "  th, td {\n"
    "    text-align: left;\n"
    "    padding: 10px var(--space-lg);\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    vertical-align: top;\n"
    "  }\n"
    "\n"
    "  th {\n"
    "    color: var(--text-secondary);\n"
    "    font-family: var(--font-mono);\n"
    "    font-weight: 600;\n"
    "    font-size: 11px;\n"
    "    text-transform: uppercase;\n"
    "    letter-spacing: 0.06em;\n"
    "    background: var(--surface-raised);\n"
    "    border-bottom: 1px solid var(--border-strong);\n"
    "  }\n"
    "\n"
    "  tr:last-child td { border-bottom: none; }\n"
    "  tr:hover td { background: var(--surface-hover); }\n"
    "\n"
    "  .sev {\n"
    "    color: #0e0e0e;\n"
    "    font-family: var(--font-mono);\n"
    "    font-weight: 700;\n"
    "    padding: 2px 7px;\n"
    "    border-radius: 4px;\n"
    "    font-size: 10px;\n"
    "    text-transform: uppercase;\n"
    "    display: inline-block;\n"
    "    letter-spacing: 0.04em;\n"
    "  }\n"
    "\n"
    "  .tool-tag {\n"
    "    font-family: var(--font-mono);\n"
    "    font-size: 12px;\n"
    "    color: var(--silver);\n"
    "    background: var(--surface-raised);\n"
    "    border: 1px solid var(--border);\n"
    "    padding: 2px 6px;\n"
    "    border-radius: 4px;\n"
    "    display: inline-block;\n"
    "  }\n"
    "\n"
    "  .type-tag { font-family: var(--font-mono); font-size: 12px; color: var(--text-secondary); }\n"
    "  .val-mono { font-family: var(--font-mono); font-size: 12px; color: var(--text-primary); word-break: break-all; }\n"
    "  td.dim { color: var(--text-secondary); font-size: 12px; }\n"
    "\n"
    "  /* Footer */\n"
    "  footer {\n"
    "    text-align: center;\n"
    "    color: var(--text-muted);\n"
    "    font-size: 12px;\n"
    "    font-family: var(--font-mono);\n"
    "    margin-top: var(--space-xl);\n"
    "  }\n"
    "\n";

#endif
